### ISSUE TITLE
Possibility to add a path to a custom key

### ISSUE THREAD

**Issue by jonnitto** [sitegeist/Sitegeist.MagicWand#11]
Sometimes there's a need for having different key files. It would be nice to have an option to set a specific key file.

**Comment by grebaldi** [comment]
This can be configured via `sshOptions`:

```yaml
Sitegeist:
  MagicWand:
    clonePresets:
      dev:
        sshOptions: '-i /path/to/my/custom/key'
```
