### ISSUE TITLE
[Enhancement] Extend flow command with placeholder

### ISSUE THREAD

**Issue by breadlesscode** [sitegeist/Sitegeist.MagicWand#41]
Hi and thanks for this great package!

What do you think about adding a placeholder for the flow command execution. Something like this:

```yaml
Sitegeist:
  MagicWand:
    flowCommand: '<FLOW_CONTEXT> ./flow <FLOW_COMMAND>'
```

If you are using Docker you can tweak your command for running in a container. I think that would be simple to achrive and really useful too :)
